version: '3.3'

services:
        webapi:
                environment:
                        - ASPNETCORE_ENVIRONMENT=Development
                ports:
                        - 8081:80

        reverse-proxy:
                ports:
                        - 80:80
